name: Display Environment

on:
  push:
    branches:
      # - develop
      # - staging
      # - main
      - "**"

jobs:
  show-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Display environment
      run: |
        if [[ "${{ github.ref_name }}" == "develop" ]]; then
          echo "Environment: Development"
        elif [[ "${{ github.ref_name }}" == "staging" ]]; then
          echo "Environment: Staging"
        elif [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "Environment: Production"
        else
          echo "Unknown environment"
        fi
